pylife_arbol:
    resource: "@PylifeBundle/Resources/config/routing/plpiramide.yml"
    prefix:   /arbol

pylife_rangos:
    resource: "@PylifeBundle/Resources/config/routing/plrango.yml"
    prefix:   /rangos

pylife_roles:
    resource: "@PylifeBundle/Resources/config/routing/plrole.yml"
    prefix:   /roles

pylife_usuarios:
    resource: "@PylifeBundle/Resources/config/routing/pluser.yml"
    prefix:   /usuarios

pylife_tipena:
    resource: "@PylifeBundle/Resources/config/routing/pltipopenalizacion.yml"
    prefix:   /tipena

pylife_penali:
    resource: "@PylifeBundle/Resources/config/routing/plpenalizacion.yml"
    prefix:   /penali

pylife_venta:
    resource: "@PylifeBundle/Resources/config/routing/plventa.yml"
    prefix:   /venta

pylife_producto:
    resource: "@PylifeBundle/Resources/config/routing/plproducto.yml"
    prefix:   /producto

pylife_posicion:
    resource: "@PylifeBundle/Resources/config/routing/plposicion.yml"
    prefix:   /posicion

pylife_premio:
    resource: "@PylifeBundle/Resources/config/routing/plpremio.yml"
    prefix:   /premio

pylife_periopre:
    resource: "@PylifeBundle/Resources/config/routing/plperiodopremio.yml"
    prefix:   /periopre

pylife_moneda:
    resource: "@PylifeBundle/Resources/config/routing/plmoneda.yml"
    prefix:   /moneda

pylife_inventario:
    resource: "@PylifeBundle/Resources/config/routing/plinventario.yml"
    prefix:   /inventario

pylife_pais:
    resource: "@PylifeBundle/Resources/config/routing/plpais.yml"
    prefix:   /pais

pylife_homepage:
    path:     /
    defaults: { _controller: PylifeBundle:Default:index }
