pylife_posicion:
    resource: "@PylifeBundle/Resources/config/routing/plposicion.yml"
    prefix:   /posicion
    
pylife_premio:
    resource: "@PylifeBundle/Resources/config/routing/plpremio.yml"
    prefix:   /premio

pylife_periopre:
    resource: "@PylifeBundle/Resources/config/routing/plperiodopremio.yml"
    prefix:   /periopre

pylife_moneda:
    resource: "@PylifeBundle/Resources/config/routing/plmoneda.yml"
    prefix:   /moneda

pylife_inventario:
    resource: "@PylifeBundle/Resources/config/routing/plinventario.yml"
    prefix:   /inventario

pylife_pais:
    resource: "@PylifeBundle/Resources/config/routing/plpais.yml"
    prefix:   /pais

pylife_homepage:
    path:     /
    defaults: { _controller: PylifeBundle:Default:index }
